/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model

import com.stuf.data.model.CommentAuthor

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param text 
 * @param author 
 * @param nestedCount 
 */


data class Comment (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "text")
    val text: kotlin.String? = null,

    @Json(name = "author")
    val author: CommentAuthor? = null,

    @Json(name = "nestedCount")
    val nestedCount: kotlin.Int? = null

) {


}

