/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model

import com.stuf.data.model.CommentAuthorDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param text 
 * @param isDeleted 
 * @param author 
 * @param nestedCount 
 */


data class CommentDto (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "text")
    val text: kotlin.String,

    @Json(name = "isDeleted")
    val isDeleted: kotlin.Boolean,

    @Json(name = "author")
    val author: CommentAuthorDto,

    @Json(name = "nestedCount")
    val nestedCount: kotlin.Int

) {


}

