/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model

import com.stuf.data.model.UserRoleType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param credentials 
 * @param email 
 * @param role 
 */


data class CourseMemberDto (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "credentials")
    val credentials: kotlin.String,

    @Json(name = "email")
    val email: kotlin.String,

    @Json(name = "role")
    val role: UserRoleType

) {


}

