/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model

import com.stuf.data.model.UserRoleType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param title 
 * @param role 
 * @param authorId 
 * @param inviteCode 
 */


data class CourseDetailsDto (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "role")
    val role: UserRoleType,

    @Json(name = "authorId")
    val authorId: java.util.UUID,

    @Json(name = "inviteCode")
    val inviteCode: kotlin.String

) {


}

