/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model

import com.stuf.data.model.PostType
import com.stuf.data.model.TaskType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param title 
 * @param text 
 * @param deadline 
 * @param maxScore 
 * @param taskType 
 * @param solvableAfterDeadline 
 * @param files 
 */


data class CreatePostRequest (

    @Json(name = "type")
    val type: PostType,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "text")
    val text: kotlin.String,

    @Json(name = "deadline")
    val deadline: java.time.OffsetDateTime? = null,

    @Json(name = "maxScore")
    val maxScore: kotlin.Int? = 5,

    @Json(name = "taskType")
    val taskType: TaskType? = null,

    @Json(name = "solvableAfterDeadline")
    val solvableAfterDeadline: kotlin.Boolean? = null,

    @Json(name = "files")
    val files: kotlin.collections.List<java.util.UUID>? = null

) {


}

