/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model

import com.stuf.data.model.CriterionDirection
import com.stuf.data.model.CriterionTypeDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param type 
 * @param title 
 * @param orderIndex 
 * @param maxScore 
 * @param weight 
 * @param threshold 
 * @param score 
 * @param direction 
 * @param maxAllowedScore 
 */


data class CriterionDefinitionDto (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "type")
    val type: CriterionTypeDto? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "orderIndex")
    val orderIndex: kotlin.Int? = null,

    @Json(name = "maxScore")
    val maxScore: kotlin.Float? = null,

    @Json(name = "weight")
    val weight: kotlin.Float? = null,

    @Json(name = "threshold")
    val threshold: kotlin.Float? = null,

    @Json(name = "score")
    val score: kotlin.Float? = null,

    @Json(name = "direction")
    val direction: CriterionDirection? = null,

    @Json(name = "maxAllowedScore")
    val maxAllowedScore: kotlin.Float? = null

) {


}

