/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param message 
 * @param `data` 
 */


data class Error (

    @Json(name = "type")
    val type: Error.Type? = null,

    @Json(name = "message")
    val message: kotlin.String? = null,

    @Json(name = "data")
    val `data`: kotlin.Any? = null

) {

    /**
     * 
     *
     * Values: error
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "error") error("error");
    }

}

