/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model

import com.stuf.data.model.ToggledValueDto
import com.stuf.data.model.WeightedValueDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param weightedValues 
 * @param toggledValues 
 */


data class EvaluationDto (

    @Json(name = "weightedValues")
    val weightedValues: kotlin.collections.List<WeightedValueDto>? = null,

    @Json(name = "toggledValues")
    val toggledValues: kotlin.collections.List<ToggledValueDto>? = null

) {


}

