/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model

import com.stuf.data.model.GradeDistributionEntryDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param teamId 
 * @param assignmentId 
 * @param teamRawScore 
 * @param propertyEntries 
 * @param sumDistributed 
 * @param distributionChanged 
 */


data class GradeDistributionResponseDto (

    @Json(name = "teamId")
    val teamId: java.util.UUID,

    @Json(name = "assignmentId")
    val assignmentId: java.util.UUID,

    @Json(name = "teamRawScore")
    val teamRawScore: kotlin.Double,

    @Json(name = "entries")
    val propertyEntries: kotlin.collections.List<GradeDistributionEntryDto>,

    @Json(name = "sumDistributed")
    val sumDistributed: kotlin.Double,

    @Json(name = "distributionChanged")
    val distributionChanged: kotlin.Boolean

) {


}

