/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param baseTeacherScore 
 * @param baseStudentScore 
 * @param baseScore 
 * @param afterQualityCoefficient 
 * @param latePenalty 
 * @param afterLatePenalty 
 * @param afterBlocking 
 * @param finalScore 
 * @param expiredDays 
 * @param thresholdApplied 
 * @param thresholdReason 
 */


data class GradeBreakdownDto (

    @Json(name = "baseTeacherScore")
    val baseTeacherScore: kotlin.Float? = null,

    @Json(name = "baseStudentScore")
    val baseStudentScore: kotlin.Float? = null,

    @Json(name = "baseScore")
    val baseScore: kotlin.Float? = null,

    @Json(name = "afterQualityCoefficient")
    val afterQualityCoefficient: kotlin.Float? = null,

    @Json(name = "latePenalty")
    val latePenalty: kotlin.Float? = null,

    @Json(name = "afterLatePenalty")
    val afterLatePenalty: kotlin.Float? = null,

    @Json(name = "afterBlocking")
    val afterBlocking: kotlin.Float? = null,

    @Json(name = "finalScore")
    val finalScore: kotlin.Float? = null,

    @Json(name = "expiredDays")
    val expiredDays: kotlin.Int? = null,

    @Json(name = "thresholdApplied")
    val thresholdApplied: kotlin.Boolean? = null,

    @Json(name = "thresholdReason")
    val thresholdReason: kotlin.String? = null

) {


}

