/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model

import com.stuf.data.model.GradeDistributionEntryDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param propertyEntries 
 */


data class GradeDistributionUpdateRequestDto (

    @Json(name = "entries")
    val propertyEntries: kotlin.collections.List<GradeDistributionEntryDto>

) {


}

