/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model

import com.stuf.data.model.EvaluationDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param userId 
 * @param credentials 
 * @param evaluation 
 */


data class MemberSelfAssessmentDto (

    @Json(name = "userId")
    val userId: java.util.UUID? = null,

    @Json(name = "credentials")
    val credentials: kotlin.String? = null,

    @Json(name = "evaluation")
    val evaluation: EvaluationDto? = null

) {


}

