/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model

import com.stuf.data.model.AnonymizedSolutionDto
import com.stuf.data.model.CriterionDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param reviewId 
 * @param taskId 
 * @param solution 
 * @param criteria 
 * @param assignedAt 
 */


data class PeerReviewTargetDto (

    @Json(name = "reviewId")
    val reviewId: java.util.UUID,

    @Json(name = "taskId")
    val taskId: java.util.UUID,

    @Json(name = "solution")
    val solution: AnonymizedSolutionDto,

    @Json(name = "criteria")
    val criteria: kotlin.collections.List<CriterionDto>,

    @Json(name = "assignedAt")
    val assignedAt: java.time.OffsetDateTime

) {


}

