/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param teamSolutionId 
 * @param teamName 
 * @param submittedAt 
 * @param alreadyReviewed 
 */


data class PeerReviewTeamTargetDto (

    @Json(name = "teamSolutionId")
    val teamSolutionId: java.util.UUID,

    @Json(name = "teamName")
    val teamName: kotlin.String,

    @Json(name = "submittedAt")
    val submittedAt: java.time.OffsetDateTime,

    @Json(name = "alreadyReviewed")
    val alreadyReviewed: kotlin.Boolean

) {


}

