/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param required 
 * @param completed 
 * @param canFinish 
 * @param isCounted 
 */


data class PeerReviewProgressDto (

    @Json(name = "required")
    val required: kotlin.Int,

    @Json(name = "completed")
    val completed: kotlin.Int,

    @Json(name = "canFinish")
    val canFinish: kotlin.Boolean,

    @Json(name = "isCounted")
    val isCounted: kotlin.Boolean

) {


}

