/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model

import com.stuf.data.model.PostType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param type 
 * @param title 
 * @param createdDate 
 */


data class PostFeedItem (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "type")
    val type: PostType? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "createdDate")
    val createdDate: java.time.OffsetDateTime? = null

) {


}

