/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model

import com.stuf.data.model.CaptainSelectionMode
import com.stuf.data.model.FileDto
import com.stuf.data.model.PostType
import com.stuf.data.model.TaskType
import com.stuf.data.model.TeamSolutionDto
import com.stuf.data.model.UserSolutionDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param title 
 * @param text 
 * @param id 
 * @param deadline 
 * @param maxScore 
 * @param taskType 
 * @param solvableAfterDeadline 
 * @param files 
 * @param userSolution 
 * @param minTeamSize 
 * @param maxTeamSize 
 * @param teamSolution 
 * @param captainMode 
 * @param votingDurationHours 
 * @param predefinedTeamsCount 
 * @param allowJoinTeam 
 * @param allowLeaveTeam 
 * @param allowStudentTransferCaptain 
 */


data class PostDetailsDto (

    @Json(name = "type")
    val type: PostType,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "text")
    val text: kotlin.String,

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "deadline")
    val deadline: java.time.OffsetDateTime? = null,

    @Json(name = "maxScore")
    val maxScore: kotlin.Int? = null,

    @Json(name = "taskType")
    val taskType: TaskType? = null,

    @Json(name = "solvableAfterDeadline")
    val solvableAfterDeadline: kotlin.Boolean? = null,

    @Json(name = "files")
    val files: kotlin.collections.List<FileDto>? = null,

    @Json(name = "userSolution")
    val userSolution: UserSolutionDto? = null,

    @Json(name = "minTeamSize")
    val minTeamSize: kotlin.Int? = null,

    @Json(name = "maxTeamSize")
    val maxTeamSize: kotlin.Int? = null,

    @Json(name = "teamSolution")
    val teamSolution: TeamSolutionDto? = null,

    @Json(name = "captainMode")
    val captainMode: CaptainSelectionMode? = null,

    @Json(name = "votingDurationHours")
    val votingDurationHours: kotlin.Int? = null,

    @Json(name = "predefinedTeamsCount")
    val predefinedTeamsCount: kotlin.Int? = null,

    @Json(name = "allowJoinTeam")
    val allowJoinTeam: kotlin.Boolean? = null,

    @Json(name = "allowLeaveTeam")
    val allowLeaveTeam: kotlin.Boolean? = null,

    @Json(name = "allowStudentTransferCaptain")
    val allowStudentTransferCaptain: kotlin.Boolean? = null

) {


}

