/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type Тип ответа (успех/ошибка)
 * @param message Сообщение для отображения на UI
 * @param `data` Данные ответа
 */


data class ResponseWrapper (

    /* Тип ответа (успех/ошибка) */
    @Json(name = "type")
    val type: ResponseWrapper.Type? = null,

    /* Сообщение для отображения на UI */
    @Json(name = "message")
    val message: kotlin.String? = null,

    /* Данные ответа */
    @Json(name = "data")
    val `data`: kotlin.Any? = null

) {

    /**
     * Тип ответа (успех/ошибка)
     *
     * Values: success,error
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "success") success("success"),
        @Json(name = "error") error("error");
    }

}

