/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param score 
 * @param status 
 * @param comment 
 */


data class ReviewRequest (

    @Json(name = "score")
    val score: kotlin.Int,

    @Json(name = "status")
    val status: ReviewRequest.Status,

    @Json(name = "comment")
    val comment: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: checked,returned
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "checked") checked("checked"),
        @Json(name = "returned") returned("returned");
    }

}

