/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model

import com.stuf.data.model.FileInfo
import com.stuf.data.model.SolutionStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param text 
 * @param files 
 * @param score 
 * @param status 
 * @param updatedDate 
 */


data class Solution (

    @Json(name = "text")
    val text: kotlin.String? = null,

    @Json(name = "files")
    val files: kotlin.collections.List<FileInfo>? = null,

    @Json(name = "score")
    val score: kotlin.Int? = null,

    @Json(name = "status")
    val status: SolutionStatus? = null,

    @Json(name = "updatedDate")
    val updatedDate: java.time.OffsetDateTime? = null

) {


}

