/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param credentials 
 */


data class SolutionWithUserUser (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "credentials")
    val credentials: kotlin.String? = null

) {


}

