/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model

import com.stuf.data.model.ApiResponseType
import com.stuf.data.model.StudentSolutionDetailsDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param message 
 * @param `data` 
 */


data class StudentSolutionDetailsDtoApiResponse (

    @Json(name = "type")
    val type: ApiResponseType,

    @Json(name = "message")
    val message: kotlin.String? = null,

    @Json(name = "data")
    val `data`: StudentSolutionDetailsDto? = null

) {


}

