/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param text 
 * @param files 
 */


data class SubmitSolutionRequestDto (

    @Json(name = "text")
    val text: kotlin.String? = null,

    @Json(name = "files")
    val files: kotlin.collections.List<java.util.UUID>? = null

) {


}

