/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model

import com.stuf.data.model.TeamMemberRole

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param userId 
 * @param credentials 
 * @param role 
 */


data class TeamMemberDto (

    @Json(name = "userId")
    val userId: java.util.UUID,

    @Json(name = "credentials")
    val credentials: kotlin.String,

    @Json(name = "role")
    val role: TeamMemberRole

) {


}

