/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model

import com.stuf.data.model.FileDto
import com.stuf.data.model.SolutionStatus
import com.stuf.data.model.TeamDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param team 
 * @param text 
 * @param status 
 * @param updatedDate 
 * @param score 
 * @param files 
 */


data class TeamSolutionListItemDto (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "team")
    val team: TeamDto,

    @Json(name = "text")
    val text: kotlin.String,

    @Json(name = "status")
    val status: SolutionStatus,

    @Json(name = "updatedDate")
    val updatedDate: java.time.OffsetDateTime,

    @Json(name = "score")
    val score: kotlin.Int? = null,

    @Json(name = "files")
    val files: kotlin.collections.List<FileDto>? = null

) {


}

