/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param role 
 */


data class UpdateRoleRequest (

    @Json(name = "role")
    val role: UpdateRoleRequest.Role

) {

    /**
     * 
     *
     * Values: teacher,student
     */
    @JsonClass(generateAdapter = false)
    enum class Role(val value: kotlin.String) {
        @Json(name = "teacher") teacher("teacher"),
        @Json(name = "student") student("student");
    }

}

