/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model

import com.stuf.data.model.SolutionStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param status 
 * @param score 
 * @param comment 
 */


data class UpdateSolutionRequestDto (

    @Json(name = "status")
    val status: SolutionStatus,

    @Json(name = "score")
    val score: kotlin.Int? = null,

    @Json(name = "comment")
    val comment: kotlin.String? = null

) {


}

