/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param oldPassword 
 * @param newPassword 
 */


data class UserChangePassword (

    @Json(name = "oldPassword")
    val oldPassword: kotlin.String? = null,

    @Json(name = "newPassword")
    val newPassword: kotlin.String? = null

) {


}

