/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param title 
 * @param role 
 */


data class UserCourse (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "role")
    val role: UserCourse.Role? = null

) {

    /**
     * 
     *
     * Values: teacher,student
     */
    @JsonClass(generateAdapter = false)
    enum class Role(val value: kotlin.String) {
        @Json(name = "teacher") teacher("teacher"),
        @Json(name = "student") student("student");
    }

}

