/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model

import com.stuf.data.model.SolutionStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param text 
 * @param score 
 * @param id 
 * @param status 
 */


data class UserSolutionDto (

    @Json(name = "text")
    val text: kotlin.String,

    @Json(name = "score")
    val score: kotlin.Int,

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "status")
    val status: SolutionStatus? = null

) {


}

