/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model

import com.stuf.data.model.UserCourseDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param records 
 * @param totalRecords 
 */


data class UserCourseDtoPagedResponse (

    @Json(name = "records")
    val records: kotlin.collections.List<UserCourseDto>,

    @Json(name = "totalRecords")
    val totalRecords: kotlin.Int

) {


}

