/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.stuf.data.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param criterionId 
 * @param score 
 */


data class WeightedValueDto (

    @Json(name = "criterionId")
    val criterionId: java.util.UUID? = null,

    @Json(name = "score")
    val score: kotlin.Float? = null

) {


}

